about/urls.py
from django.urls import path
from . import views
from .views import AboutDetailView
app_name ='about'


urlpatterns = [
    path('', AboutDetailView.as_view(), name='about_us'),
]

account/urls.py
from django.urls import path
from . import views
app_name ='account'


urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.userlogout, name="logout"),
    path('profile', views.userprofile, name ="profile"),
    path('change/password', views.change_password_view, name='change_password'),
]

app/urls.py
from django.urls import path
from . import views
from .views import IndexView,SolutionDetailView,SolutionSubDetailView,SectorbDetailView,LocationsList,TestimonialsListView
app_name ='app'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about-us',views.aboutus, name='about'),
    path('solution',views.solution, name='solution'),
    path('solution/<slug:slug>',SolutionDetailView.as_view(), name='solution_detail'),
    path('solution/detail/<slug:slug>',SolutionSubDetailView.as_view(), name='solution_sub_detail'),
    path('sectors', views.sectors, name='sectors'),
    path('sectors/<slug:slug>', SectorbDetailView.as_view(), name='sector_detail'),
    path('location', LocationsList.as_view(), name='location'),
    path('testimonials', TestimonialsListView.as_view(), name='testimonials'),
]

app2/urls.py
from django.urls import path
from . import views 
from . views import *


app_name ='dashboard'

urlpatterns = [
        path('',views.index,name='index'),

        path('banners/', BannarListView.as_view(), name="banners"),
        path('banners/create', BannerCreateView.as_view(), name='banner_create'),
        path('banners/delete/<int:id>', views.delete_banner, name='banner_delete'),

        path('about/', views.aboutUs, name='about'),
        path('about/organizatin/setting', views.organizationsetting, name='organizations_setting'),
        path('about/objectives/add',ObjectiveCreatView.as_view(), name='objective_create'),
        path('about/objective',ObjectivesListView.as_view(), name='objective'),
        path('about/objective/detail/<int:id>',ObjectivesDetailView.as_view(), name='objective_detail'),
        path('about/objective/delete/<int:id>', views.objective_delete, name='objective_delete'),
        path('location', LocationListView.as_view(), name='locations'),
        path('location/add', LocationCreateView.as_view(), name='add_new_location'),
        path('location/update/<int:id>',LocationUpdateDetailView.as_view(), name='location_detail_update'),
        path('location/delete/<int:id>', views.location_delete, name='delete_location'),
        path('office', OfficeLocationListView.as_view(), name='office'),
        path('office/add', OfficeLocationCreateView.as_view(), name='add_office'),
        path('office/update/<int:id>',OfficeUpdateDetailView.as_view(),name='office_detail_update'),
        path('office/delete/<int:id>',views.office_delete, name='office_delete'),

        path('career/category', CareerCategoryListView.as_view(), name='career_category'),
        path('career/category/delete/<int:id>',views.delete_career_category, name='delete_category'),
        path('career/category/update',views.update_category, name='category_update'),

        path('careers', CareerListView.as_view(), name='careers_list'),
        path('careers/add',CareerCreateView.as_view(), name='career_create'),
        path('careers/update/<int:id>',CareerUpdateView.as_view(), name='career_update'),
        path('careers/delete/<int:id>', views.delete_career,name='delete_career'),

        path('testimonials', TestimonialsListView.as_view(), name='testimonials'),
        path('testimonials/add', TestimonialsCreateView.as_view(), name='testimonials_add'),
        path('testimonials/update/<int:id>', TestimonialsUpdateView.as_view(), name='testimonials_update'),
        path('testimonials/delete/<int:id>', views.delete_testimonials, name='delete_testimonials'),

        path('clients', ClientListCreateView.as_view(), name='client_list'),
        path('clients/delete/<int:id>',views.delete_client, name='delete_client'),


        path('resources/<slug:resource_type>',NewsResourcesListView.as_view(), name='resources_news'),
        path('resources/create/<slug:resource_type>/', NewsResourcesCreateView.as_view(), name='news_resources_create'),
        path('resources/update/<slug:slug>',NewsResourcesUpdateView.as_view(), name='resource_update'),
        path('resources/delete/<slug:slug>', views.delete_resources,name='delete_resources'),


        path('about/sector', views.aboutSector, name='about_sector'),
        path('sectors',SectorListView.as_view(), name='sectors'),
        path('sectors/create',SectorCreateView.as_view(), name='sector_create'),
        path('sectors/update/<slug:slug>',SectorUpdateView.as_view(), name='update_sector'),
        path('sectors/delete/<slug:slug>', views.delete_sectors, name='delete_sectors'),


        path('about/solution', views.aboutSolution, name='solution'),
        path('solutions', SolutionListView.as_view(), name='solution_list'),
        path('solutions/create', SolutionCreateView.as_view(), name='solution_create'),
        path('solutions/update/<slug:slug>', SolutionUpdateView.as_view(), name='solution_update'),
        path('solutions/delete/<slug:slug>', views.delete_solution, name='delete_solution'),


        path('solution/sub-category',SolutionSubCategoryListView.as_view(), name='solution_sub_category'),
        path('solution/sub-category/create',SolutionSubCategoryCreateView.as_view(), name='solution_sub_category_create'),
        path('solution/sub-category/update/<slug:slug>',SolutionSubCategoryUpdateView.as_view(), name='solution_sub_category_update'),
        path('solution/sub-category/delete/<slug:slug>', views.delete_SolutionSubCategor, name='delete_solution_sub_category'),


        path('associated/company',AssocialtedCompanyListView.as_view(), name='associated_company_list'),
        path('associated/company/create',AssociatedCreateView.as_view(), name='associated_company_create'),
        path('associated/compnay/update/<int:id>',AssociatedCompanyUpdateView.as_view(), name='associated_company_update'),
        path('associated/company/delete/<int:id>', views.delete_Associated_company, name='associated_company_delete'),


]

careers/urls.py
from django.urls import path
from . import views
from .views import CareersListView,CareerDetailView
app_name ='careers'


urlpatterns = [
    path('', CareersListView.as_view(), name='careers'),
    path('<slug:slug>', CareerDetailView.as_view(), name='career_detail'),
]

app2/models.py
from django.db import models

# Create your models here.

about/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from about.models import About,Objective
from news.models import Resources
from app.models import Client
from django.views import generic


class AboutDetailView(generic.DetailView):
    model = About
    template_name = 'about/about.html'
    context_object_name = 'about_us'  

    def get_object(self, queryset=None):
        return About.objects.first() 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['about_us'] = self.get_object()
        context['objectives'] = Objective.objects.all()
        context['resources'] = Resources.objects.all()[:4]
        context['clients'] = Client.objects.all()
        return context

app2/views.py
from django.http import HttpRequest
from django.shortcuts import render,HttpResponse, HttpResponseRedirect,redirect,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views import View
from . decorators import login_required
from django.contrib import messages
from . forms import *
from app.models import *
from about.models import *
from careers.models import *
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import Paginator
from django.views import generic
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator


''''index page'''
@login_required
def index(request):
    return render(request,'app2/index.html')



'''bannar '''
class BannarListView(generic.ListView):
    model = Banner
    context_object_name ='banners'
    template_name ='app2/banner.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = BannerForm()  
        return context
    

class BannerCreateView(generic.CreateView):
    model = Banner
    form_class = BannerForm
    
    def get_success_url(self) -> str:
        messages.success(self.request,'Banner Created successfully !')
        return reverse_lazy('dashboard:banners')

@login_required
def delete_banner(request, id):
    instance = get_object_or_404(Banner, id=id)
    instance.delete()
    messages.success(request, "Deleted Successfully!")
    return redirect('dashboard:banners')

    
    
''' about organization'''
@login_required
def aboutUs(request):
    instance = None
    try:
        if id:
            instance = About.objects.first()
    except Exception as e:
        messages.warning(request, 'An error occurred while retrieving the AboutUS.')
        return redirect('dashboard:aboutUs')

    if request.method == 'POST':
        form = AboutUSForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            if instance: 
                messages.success(request, 'AboutUS edited successfully.')
                return redirect('dashboard:about') 
            else: 
                messages.success(request, 'AboutUS added successfully.')
                return redirect('dashboard:about') 
        else:
            messages.warning(request, 'Form is not valid. Please correct the errors.')
    else:
        form = AboutUSForm(instance=instance)

    context = {'form': form, 'instance': instance}
    return render(request, 'app2/create_about_us.html', context)

'''organization settings '''
@login_required
def organizationsetting(request):
    instance = None
    try:
        if id:
            instance = OrganizationSetting.objects.first()
    except Exception as e:
        messages.warning(request, 'An error occurred while retrieving the AboutUS.')
        return redirect('dashboard:organizations_setting')

    if request.method == 'POST':
        form = OrganizationSettingForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            if instance: 
                messages.success(request, 'AboutUS edited successfully.')
                return redirect('dashboard:organizations_setting') 
            else: 
                messages.success(request, 'AboutUS added successfully.')
                return redirect('dashboard:organizations_setting') 
        else:
            messages.warning(request, 'Form is not valid. Please correct the errors.')
    else:
        form = OrganizationSettingForm(instance=instance)

    context = {'form': form, 'instance': instance}
    return render(request, 'app2/organization_setting.html', context)

'''objectives '''
@method_decorator(login_required, name='dispatch')
class ObjectiveCreatView(generic.CreateView):
    model = Objective
    template_name = 'app2/objectivs_detail.html'
    form_class = ObjectiveForm
    def get_success_url(self):
        return reverse_lazy('dashboard:objective')
    
@method_decorator(login_required, name='dispatch')
class ObjectivesListView(generic.ListView):
    model = Objective
    template_name ='app2/objectivs.html'
    context_object_name ='objectives'
    paginate_by =5

@method_decorator(login_required, name='dispatch')
class ObjectivesDetailView(generic.UpdateView):
    model = Objective
    template_name ='app2/objectivs_detail.html'
    context_object_name ='objective_detail'
    pk_url_kwarg ='id'
    form_class = ObjectiveForm
    def get_success_url(self):
        messages.success(self.request,'Updated Successfully !')
        return reverse_lazy('dashboard:objective_detail', kwargs={'id': self.object.id})

@login_required
def objective_delete(request, id):
    objective = get_object_or_404(Objective, id=id)
    objective.delete()
    messages.success(request, "Deleted Successfully!")
    return redirect('dashboard:objective')



'''' Location '''
@method_decorator(login_required, name='dispatch')
class LocationListView(generic.ListView):
    model = Location
    template_name ='app2/location.html'
    context_object_name ='locations'


@method_decorator(login_required, name='dispatch')
class LocationCreateView(generic.CreateView):
    model = Location
    template_name ='app2/location_form.html'
    form_class = LocationForm
    def get_success_url(self):
        return reverse_lazy('dashboard:locations')
    

@method_decorator(login_required, name='dispatch')
class LocationUpdateDetailView(generic.UpdateView):
    model = Location
    template_name ='app2/location_form.html'
    pk_url_kwarg ='id'
    form_class = LocationForm
    def get_success_url(self):
        messages.success(self.request,'Updated Successfully !')
        return reverse_lazy('dashboard:location_detail_update', kwargs={'id': self.object.id})

@login_required
def location_delete(request, id):
    instance = get_object_or_404(Location, id=id)
    instance.delete()
    messages.success(request, "Deleted Successfully!")
    return redirect('dashboard:locations')


''' office section '''
@method_decorator(login_required, name='dispatch')
class OfficeLocationListView(generic.ListView):
    model = Office
    template_name ='app2/office.html'
    context_object_name ='office_locations'


@method_decorator(login_required, name='dispatch')
class OfficeLocationCreateView(generic.CreateView):
    model = Office
    template_name ='app2/office_form.html'
    form_class = OfficeForm
    def get_success_url(self):
        return reverse_lazy('dashboard:office')

@method_decorator(login_required, name='dispatch')
class OfficeUpdateDetailView(generic.UpdateView):
    model = Office
    template_name ='app2/office_form.html'
    pk_url_kwarg ='id'
    form_class = OfficeForm
    def get_success_url(self):
        messages.success(self.request,'Updated Successfully !')
        return reverse_lazy('dashboard:office_detail_update', kwargs={'id': self.object.id})


@login_required
def office_delete(request, id):
    instance = get_object_or_404(Office, id=id)
    instance.delete()
    messages.success(request, "Deleted Successfully!")
    return redirect('dashboard:office')


''' career category '''
@method_decorator(login_required, name='dispatch')
class CareerCategoryListView(generic.ListView):
    model = Category
    context_object_name ='categories'
    template_name ='app2/career_category.html'

    def get_context_data(self, *args, **kwargs):
        context= super().get_context_data(**kwargs)
        context['form'] = CareerCategoryForm
        return context
    
    def post(self, request, *args, **kwargs):
        form = CareerCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return self.get(request, *args, **kwargs)
        else:
            return self.render_to_response(self.get_context_data(form=form))
        
@login_required
def update_category(request):
    if request.method =="POST":
        id = request.POST.get('category_id')
        instance = Category.objects.get(id=id)
        instance.category_name = request.POST.get('category_name')
        instance.save()
        return redirect('dashboard:career_category')
    else:
        return redirect('dashboard:career_category')
    
@login_required   
def delete_career_category(request,id):
    instance = Category.objects.get(id=id)
    instance.delete()
    messages.success(request,'Category Delete Successfully !')
    return redirect('dashboard:career_category')


''' Careers '''
@method_decorator(login_required, name='dispatch')
class CareerListView(generic.ListView):
    model = Careers
    template_name ='app2/careers.html'
    context_object_name ='careers'
    paginate_by =5


@method_decorator(login_required, name='dispatch')
class CareerCreateView(generic.CreateView):
    model = Careers
    template_name ='app2/career_form.html'
    form_class = CareerForm
    def get_success_url(self):
        messages.success(self.request,"Career Added Successfully !")
        return reverse_lazy('dashboard:careers_list')



@method_decorator(login_required, name='dispatch')
class CareerUpdateView(generic.UpdateView):
    model = Careers
    template_name ='app2/career_form.html'
    pk_url_kwarg ='id'
    form_class = CareerForm
    def get_success_url(self):
        messages.success(self.request,'Career Updated Successfully !')
        return reverse_lazy('dashboard:career_update', kwargs={'id': self.object.id})
    

@login_required
def delete_career(request,id):
    Careers.objects.get(id=id).delete()
    messages.success(request,"Deleted Successfully !")
    return redirect('dashboard:careers_list')

    
'''testimonials '''
@method_decorator(login_required, name='dispatch')
class TestimonialsListView(generic.ListView):
    model = Testimonials
    template_name ='app2/testimonials.html'
    context_object_name ='testimonials'
    paginate_by =5

@method_decorator(login_required, name='dispatch')

app2/templates/app2/location.html
{% extends 'app2/base.html' %}
{% load static %}
{% block title %} 
Our  Office Locations 
{% endblock %}
{% block body %}

<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row pt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <div class="fs-3">Our Locations </div>
                                </div> 
                                <div class="col-sm-6">
                                    <a href="{% url 'dashboard:add_new_location' %}" class="btn btn-success mb-2 float-end rounded-0"><i class="mdi mdi-plus-circle me-2"></i> Add New Objective</a>
                                </div> 
                            </div>
                        
                            <div class="tab-content ">
                                <table id="datatable-buttons" class="table table-striped dt-responsive nowrap w-100 ">
                                    <thead>
                                        <tr>
                                            <th >S.N</th>
                                            <th>Logo</th>
                                            <th class="text-nowrap">Company Name</th>
                                            <th>Country</th>
                                            <th>Address</th>
                                            <th style="width: 200px;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {%for location in locations%}
                                    <tr>
                            
                                        <td>
                                            {{forloop.counter}}
                                        </td>
                                        <td>
                                            <div class="image-gallery" style="width:auto">
                                                <img class="thumbnail" src="{{location.logo.url}}" style="height: 200px; width: auto;" alt="Thumbnail Image">
                                            </div>
                                            <div class="modal" id="imageModal">
                                                <span class="close-btn" onclick="closeModal()">&times;</span>
                                                <img class="modal-content" id="modalImage">
                                            </div>
                                        
                                            <script src="script.js"></script>
                                        </td>
                                        <td style="width:auto; text-align:justify;">
                                            {{location.company_name|safe}}
                                        </td>
                                        <td style="width:auto; text-align:justify;">
                                            {{location.country}}
                                        </td>
                                        <td style="width:auto; text-align:justify;">
                                            {{location.address}}
                                        </td>
                                    
                                    
                                        
                                    
                                        <td>
                                            <a href="" class="action-icon"> <i class="mdi mdi-eye"></i></a>
                                            <a href="{% url 'dashboard:location_detail_update' location.id %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                            <a href="{% url 'dashboard:delete_location' location.id %}" class="action-icon"> <i class="mdi mdi-delete"></i></a>
                                        </td>
                                    </tr>
                                    {%endfor%}
                                    </tbody>
                                </table>                                           
                                
                            </div> 
                            <!-- end tab-content-->
                            
                        </div> <!-- end card body-->
                    </div> <!-- end card -->
                </div><!-- end col-->
            </div> <!-- end row-->



        </div> <!-- container -->
    </div> <!-- content -->
</div>

{%endblock%}

app2/templates/app2/resources_list.html
{% extends 'app2/base.html' %}
{% load static %}
{% block title %} 
Resources {{resource_type}}
{% endblock %}
{% block body %}

<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row pt-3">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <div class="fs-3 text-capitalize">Our {{resource_type}} </div>
                                </div> 
                                <div class="col-sm-6">
                                    <a href="{% url 'dashboard:news_resources_create' resource_type %}" class="btn btn-success mb-2 float-end rounded-0 text-capitalize"><i class="mdi mdi-plus-circle me-2"></i> Add {{resource_type}}</a>
                                </div> 
                            </div>
                        
                            <div class="tab-content ">
                                {% if messages %}
                                    {% for msg in messages %}
                                        <div class="alert alert-{{ msg.tags }} alert-dismissible text-bg-{{ msg.tags }} border-0 fade show" role="alert">
                                            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                                            <strong>{% if msg.tags == 'success' %}Success{% elif msg.tags == 'warning' %}Warning{% endif %} - </strong>{{ msg.message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                                <table id="datatable-buttons" class="table table-striped dt-responsive nowrap w-100 ">
                                    <thead>
                                        <tr>
                                            <th >S.N</th>
                                            <th>Title</th>
                                            <th>Image</th>
                                            <th>Description</th>
                                            <th style="width: 170px;">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {%for news in page_obj  %}
                                    <tr>
                            
                                        <td>
                                            {{forloop.counter}}
                                        </td>
                                       
                                        <td style="width:auto; text-align:justify;">
                                            {{news.title}}
                                        </td>
                                        <td>
                                            <div class="image-gallery" style="width:auto">
                                                <img class="thumbnail" src="{{news.image.url}}" style="height: 200px; width: auto;" alt="Thumbnail Image">
                                            </div>
                                            <div class="modal" id="imageModal">
                                                <span class="close-btn" onclick="closeModal()">&times;</span>
                                                <img class="modal-content img-fluid" id="modalImage">
                                            </div>
                                        
                                            <script src="script.js"></script>
                                        </td>
                                        <td style="width:auto; text-align:justify;">
                                            {{news.descriptions|safe|truncatewords:20}}
                                        </td>
                                    
                                    
                                        
                                    
                                        <td>
                                            <a href="{% url 'dashboard:resource_update' news.slug %}" class="action-icon"> <i class="mdi mdi-square-edit-outline"></i></a>
                                            <button type="button"  data-bs-toggle="modal" data-bs-target="#resourceDeleteModal_{{news.id}}" class="border-0 text-danger float-end rounded-0">
                                                <i class="mdi mdi-delete"></i>
                                            </button>
                                        </td>
                                    </tr>

                                    <!--delete client Modal -->
                                    <div class="modal fade " id="resourceDeleteModal_{{news.id}}" tabindex="-1" aria-labelledby="resourceDeleteModalLabel" aria-hidden="true">
                                        <div class="modal-dialog  h-50"  >
                                            <div class="modal-content " style="background: white; padding: 20px;" >
                                                <strong class="fs-5">Are your for deleting these client ?</strong>
                                                <a href="{% url 'dashboard:delete_resources' news.slug %}" class="action-icon btn btn-danger w-50 mt-2 float-center">Delete</a>

                                            </div>
                                        </div>
                                    </div>
                                    <!-- end client delete modal-->
                                    {%endfor%}
                                    </tbody>
                                </table>   

                                <!-- Pagination Controls -->
                                {% if is_paginated %}
                                <nav aria-label="Page navigation">
                                    <ul class="pagination">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                                            </li>
                                        {% endif %}
                                        
                                        {% for num in page_obj.paginator.page_range %}
                                            {% if num == page_obj.number %}
                                                <li class="page-item active">
                                                    <span class="page-link">{{ num }}</span>
                                                </li>
                                            {% else %}
                                                <li class="page-item">
                                                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                        
                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                                {% endif %}
                                                            
                                                            
                                
                            </div> 
                            <!-- end tab-content-->
                            
                        </div> <!-- end card body-->
                    </div> <!-- end card -->
                </div><!-- end col-->
            </div> <!-- end row-->



        </div> <!-- container -->
    </div> <!-- content -->
</div>

{%endblock%}