Goldplayers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('about/',include('about.urls')),
    path('resources/', include('news.urls')),
    path('account/', include('account.urls')),
    path('careers/', include('careers.urls')),
    path('dashboard/',include('app2.urls')),
    path('ckeditor/' ,include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views
from .views import IndexView,SolutionDetailView,SolutionSubDetailView,SectorbDetailView,LocationsList,TestimonialsListView
app_name ='app'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about-us',views.aboutus, name='about'),
    path('solution',views.solution, name='solution'),
    path('solution/<slug:slug>',SolutionDetailView.as_view(), name='solution_detail'),
    path('solution/detail/<slug:slug>',SolutionSubDetailView.as_view(), name='solution_sub_detail'),
    path('sectors', views.sectors, name='sectors'),
    path('sectors/<slug:slug>', SectorbDetailView.as_view(), name='sector_detail'),
    path('location', LocationsList.as_view(), name='location'),
    path('testimonials', TestimonialsListView.as_view(), name='testimonials'),
]

news/urls.py
from django.urls import path
from . import views
from .views import ResourcseListView,ResourceDetailView,NewsResourcseListView,InsightsResourcseListView,CaseStudiesResourcseListView
app_name ='resources'


urlpatterns = [
    path('', ResourcseListView.as_view(), name='all_resources'),
    path('detail/<slug:slug>', ResourceDetailView.as_view(), name='resource_detail'),
    path('news',NewsResourcseListView.as_view(), name='resources_news'),
    path('insights',InsightsResourcseListView.as_view(), name='resources_insight'),
    path('case-studies',CaseStudiesResourcseListView.as_view(), name='resources_case_studies'),

]

news/models.py
from django.db import models
from ckeditor.fields import RichTextField
from autoslug import AutoSlugField

RESOURCES_TYPE =[
    ('news','News'),
    ('insights','Insights'),
    ('case_studies','Case Studies')
]

'''RESOURCES model'''
class Resources(models.Model):
    resource_type = models.CharField(max_length=150, verbose_name='Select Resource Type',choices=RESOURCES_TYPE, default='news')
    title = models.CharField(max_length=150, verbose_name='Title')
    image = models.ImageField(upload_to='resourcesimage/',verbose_name='Select Image')
    descriptions = RichTextField(verbose_name='Descriptions')
    slug = AutoSlugField(populate_from ='title', default=None, unique=True)


    class Meta:
        ordering =['id']
        verbose_name='Resources'
        verbose_name_plural = 'Resources'

    def __str__(self) -> str:
        return self.title
    
    

        

news/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from . models import Resources
from django.views import generic


class ResourcseListView(generic.ListView):
    model = Resources
    template_name ='news/resources.html'
    context_object_name ='resources'
    paginate_by =3


class ResourceDetailView(generic.DetailView):
    model = Resources 
    template_name ='news/resource_detail.html'
    context_object_name ='resource_detail'
    slug_url_kwarg = 'slug' 

''' news related rescources '''
class NewsResourcseListView(generic.ListView):
    model = Resources
    template_name ='news/resources.html'
    context_object_name ='resources'
    paginate_by =3

    def get_queryset(self):
        return Resources.objects.filter(resource_type='news')
    

''' insights related rescources '''
class InsightsResourcseListView(generic.ListView):
    model = Resources
    template_name ='news/resources.html'
    context_object_name ='resources'
    paginate_by =3

    def get_queryset(self):
        return Resources.objects.filter(resource_type='insights')
    

''' case studies related rescources '''
class CaseStudiesResourcseListView(generic.ListView):
    model = Resources
    template_name ='news/resources.html'
    context_object_name ='resources'
    paginate_by =3

    def get_queryset(self):
        return Resources.objects.filter(resource_type='case_studies')

news/templates/news/resource_detail.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}
Blog Detail 
{% endblock %}
{% block content %}
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs"  style="
    background-image:url(https://4984701.fs1.hubspotusercontent-na1.net/hubfs/4984701/Imdaad_2019/Images/Blog/News-01-01-01.jpg);
    background-size:cover;">
      <div class="container">

        <ol>
          <li><a href="/" class="text-white"> Home</a></li>
          <li><a href="{% url  'resources:all_resources' %}" class="text-white">Resources</a></li>
        </ol>
        <h2 class="text-white">{{resource_detail.title}}</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= Blog Single Section ======= -->
    <section class="pt-0" 
      style="background-image:url('https://4984701.fs1.hubspotusercontent-na1.net/hubfs/4984701/Imdaad_2019/Images/Blog/line_bg.png')">
    </section>

    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-12 entries">

            <article class="entry entry-single">

              <div class="">
                <img src="{{resource_detail.image.url}}" alt="" class="img-fluid w-100">
              </div>
              <br>
              <h2 class="entry-title">
                <a href="{% url 'resources:resource_detail' resource_detail.slug %}">{{resource_detail.title}}</a>
              </h2>
            

              

              <div class="entry-content">
                <p>
                  {{resource_detail.descriptions|safe}}
                </p>

                
               

               
            </article><!-- End blog entry -->

           
           
          </div><!-- End blog entries list -->

          
        </div>

      </div>
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->
{% endblock %}

news/templates/news/resources.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}
Blogs 
{% endblock %}
{% block content %}
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs" style="
      background-image:url(https://4984701.fs1.hubspotusercontent-na1.net/hubfs/4984701/Imdaad_2019/Images/Blog/News-01-01-01.jpg);
      background-size:cover;">
      <div class="container ">

        <ol>
          <li><a href="/" class="text-white">Home</a></li>
          <li class="text-white">Resource</li>
        </ol>
        <center>
          <h2 class="text-white bg-danger w-50 p-3">Our Resource</h2>
        </center>

      </div>
    </section>
    <!-- End Breadcrumbs -->

    <!-- ======= Blog Section ======= -->
    <section class="pt-0" style="background-image:url('https://4984701.fs1.hubspotusercontent-na1.net/hubfs/4984701/Imdaad_2019/Images/Blog/line_bg.png')">

    </section>
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        {% for resource in resources %}
        <div class="row shadow p-2 bg-white rounded">
          <div class="col-md-3">
            <img src="{{resource.image.url}}" alt="" class="img-fluid">
          </div>
          <div class="col-md-9">
            <h4 class="entry-title">
              <a href="{% url 'resources:resource_detail' resource.slug %}">{{resource.title}}</a>
            </h4>
            <div class="entry-content">
              <p>
                  {{resource.descriptions|safe|truncatewords:50}}
              </p>
              <div class="read-more">
                <a href="{% url 'resources:resource_detail' resource.slug %}">Read More</a>
              </div>
            </div>
          </div>
        </div>

        
        <br>
        {% endfor %}

        

        <div class="blog-pagination">
          {% if is_paginated %}
          <ul class="pagination justify-content-center">
              {% if page_obj.has_previous %}
                  <li class="page-item">
                      <a class="" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                  </li>
              {% else %}
                  <li class="page-item disabled">
                      <a class="" href="#">&laquo;</a>
                  </li>
              {% endif %}

              {% for i in paginator.page_range %}
                  {% if page_obj.number == i %}
                      <li class="page-item active"><a >{{ i }}</a></li>
                  {% else %}
                      <li class="page-item">
                          <a class="" href="?page={{ i }}">{{ i }}</a>
                      </li>
                  {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
                  <li class="page-item">
                      <a href="?page={{ page_obj.next_page_number }}" class="">&raquo;</a>
                  </li>
              {% else %}
                  <li class="page-item disabled">
                      <a class="">&raquo;</a>
                  </li>
              {% endif %}
          </ul>
      {% endif %}

        </div>
        

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  {% endblock %}
 