Goldplayers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('about/',include('about.urls')),
    path('resources/', include('news.urls')),
    path('account/', include('account.urls')),
    path('careers/', include('careers.urls')),
    path('dashboard/',include('app2.urls')),
    path('ckeditor/' ,include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from . import views
from .views import IndexView,SolutionDetailView,SolutionSubDetailView,SectorbDetailView,LocationsList,TestimonialsListView
app_name ='app'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about-us',views.aboutus, name='about'),
    path('solution',views.solution, name='solution'),
    path('solution/<slug:slug>',SolutionDetailView.as_view(), name='solution_detail'),
    path('solution/detail/<slug:slug>',SolutionSubDetailView.as_view(), name='solution_sub_detail'),
    path('sectors', views.sectors, name='sectors'),
    path('sectors/<slug:slug>', SectorbDetailView.as_view(), name='sector_detail'),
    path('location', LocationsList.as_view(), name='location'),
    path('testimonials', TestimonialsListView.as_view(), name='testimonials'),
]

careers/urls.py
from django.urls import path
from . import views
from .views import CareersListView,CareerDetailView
app_name ='careers'


urlpatterns = [
    path('', CareersListView.as_view(), name='careers'),
    path('<slug:slug>', CareerDetailView.as_view(), name='career_detail'),
]

careers/models.py
from django.db import models
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField

''' career category'''
class Category(models.Model):
    category_name = models.CharField(verbose_name='Career Category Name' ,max_length=150)


    def __str__(self):
        return self.category_name
    
''' career types '''
JOB_TYPE_CHOICES = [
        ('full_time', 'Full Time'),
        ('part_time', 'Part Time'),
        ('freelance', 'Freelance'),
        ('internship','Internship'),
        ('temporary','Temporary')
    ]


'''career model '''
class Careers(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=None, null=True, blank=True, verbose_name='Choose Career Category')
    company_logo = models.ImageField(upload_to='careerimage/', verbose_name='Company Logo *')
    job_title = models.CharField(verbose_name='Job Title *', max_length=150)
    location = models.CharField(verbose_name='Location *', max_length=150)
    salary = models.CharField(verbose_name='Salary *', max_length=150, null=True, blank=True)
    created_date = models.DateTimeField(auto_now=True)
    valid_date = models.DateField(verbose_name='Valid Date *')
    job_type = models.CharField(verbose_name='Job Type *', max_length=20, choices=JOB_TYPE_CHOICES, default='full_time')
    descriptions = RichTextField(verbose_name='Job Descriptions(responsibility,qualification) *')
    slug = AutoSlugField(populate_from ='job_title', default=None, unique=True)

    class Meta:
        ordering =['-id']

    def __str__(self):
        return str(self.job_title)
    

careers/views.py
from typing import Any
from django.shortcuts import render
from . models import Careers
from django.views import generic
from .froms import JobSearchForm


'''careers view '''
class CareersListView(generic.ListView):
    model = Careers
    template_name ='careers/careers.html'
    context_object_name= 'careers'
    paginate_by =5

    def get_queryset(self):
        queryset = super().get_queryset()
        form = JobSearchForm(self.request.GET)

        if form.is_valid():
            keywords = form.cleaned_data.get('keywords')
            location = form.cleaned_data.get('location')
            category = form.cleaned_data.get('category')

            if keywords:
                queryset = queryset.filter(job_title__icontains=keywords)
            if location:
                queryset = queryset.filter(location__icontains=location)
            if category:
                queryset = queryset.filter(category=category)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = JobSearchForm(self.request.GET)
        return context

'''career detail'''
class CareerDetailView(generic.DetailView):
    model = Careers 
    template_name ='careers/career_detail.html'
    context_object_name ='career_detail'
    slug_url_kwarg = 'slug'

careers/templates/careers/career_detail.html
{% extends 'app/base.html' %}
{% load static %} 
{% block title %}
{{career_detail.job_title}} 
{% endblock %}
{% block content %}
<style>
    .form-control{
        width: 100%;
    padding: 10px;
    border: 1px solid #ddd;
    }

    .job_types {
        display:flex; 
        zoom: 1;
        background: #f9f9f9;
        border-top: 1px solid #e5e5e5;
        font-size: .83em;
        list-style: none outside;
        margin: 0;
        padding: 0;
    }
</style>
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs" style="
      background-image:url(https://4984701.fs1.hubspotusercontent-na1.net/hubfs/4984701/Imdaad_2019/Images/Blog/News-01-01-01.jpg);
      background-size:cover;">
      <div class="container ">

        <ol>
          <li><a href="/" class="text-white">Home</a></li>
          <li class="text-white"><a href="{% url 'careers:careers' %}">Careers</a></li>
        </ol>
        <center>
          <h2 class="text-white bg-danger w-50 p-3">{{career_detail.job_title}}</h2>
        </center>

      </div>
    </section>
    <!-- End Breadcrumbs -->
    <!-- Careers detail  start -->
   
    <section id="blog" class="blog pt-2" >
        <div class="container" data-aos="fade-up">
            <div class="row bg-white  py-2  ">
                <div class="col-md-12 py-2 small text-muted">
                    {{career_detail.created_date}}
                </div>
                <div class="col-md-2 py-2">
                    <i class="bi bi-geo-alt fs-4 text-dark"></i>{{career_detail.location}}
                </div>
                <div class="col-md-auto py-2">
                    <i class="bi bi-calendar3"></i> Posted 1 Month ago
                </div>
                <div class="col-md-12 py-2">
                    {{career_detail.descriptions|safe}}
                </div>
                <center>
                    <a class="btn btn-outline-dark text-center w-25" href="{% url 'careers:careers' %}">Back To Career</a>
                </center>

            </div>
        </div>
    </section>

</main>
<!-- End #main -->

{% endblock %}

careers/templates/careers/careers.html
{% extends 'app/base.html' %}
{% load static %} 
{% block title %}
Careers 
{% endblock %}
{% block content %}
<style>
    .form-control{
        width: 100%;
    padding: 10px;
    border: 1px solid #ddd;
    }

    .job_types {
        display:flex; 
        zoom: 1;
        background: #f9f9f9;
        border-top: 1px solid #e5e5e5;
        font-size: .83em;
        list-style: none outside;
        margin: 0;
        padding: 0;
    }
    .form-control{
        border-color: black;
        outline-color: none;
        box-shadow: none;
        border-radius: 0px;
    
    }
</style>
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs" style="
      background-image:url(https://4984701.fs1.hubspotusercontent-na1.net/hubfs/4984701/Imdaad_2019/Images/Blog/News-01-01-01.jpg);
      background-size:cover;">
      <div class="container ">

        <ol>
          <li><a href="/" class="text-white">Home</a></li>
          <li class="text-white">Careers</li>
        </ol>
        <center>
          <h2 class="text-white bg-danger w-50 p-3">Careers</h2>
        </center>

      </div>
    </section>
    <!-- End Breadcrumbs -->
    <!-- Careers Section  start -->
    <div class="container">
        <form method="GET" action="{% url 'careers:careers' %}">

        <div class="row justify-content-between p-5" style="background: #ededed;">
            <div class="col-md-12 text-center">
                <h4>COME WORK WITH US </h4>
            </div>

            <div class="col-md-6 pt-2 pb-2">
                {{ form.keywords }}
            </div>
            <div class="col-md-6 pt-2 pb-2">
                {{ form.location }}

            </div>

            <div class="col-md-12 pt-2 pb-2">
                {{ form.category }}

            </div>

            <div class="col-md-12 my-3 text-center">
                <button type="submit" class="btn btn-dark">Search Job</button>
            </div>
            </form>
            <div class="col-md-12  ">
                <ul class=" d-flex justify-content-between job_types p-3">
					<li><label class=" pe-2 freelance"><input class="shadow-none" type="checkbox" name="filter_job_type[]" value="freelance" checked="checked" id="job_type_freelance"> Freelance</label>|</li>
					<li><label class=" pe-2 full-time"><input class="shadow-none" type="checkbox" name="filter_job_type[]" value="full-time" checked="checked" id="job_type_full-time"> Full Time</label>| </li>
					<li><label  class=" pe-2 internship"><input class="shadow-none" type="checkbox" name="filter_job_type[]" value="internship" checked="checked" id="job_type_internship"> Internship</label>| </li>
					<li><label class=" pe-2 part-time"><input class="shadow-none" type="checkbox" name="filter_job_type[]" value="part-time" checked="checked" id="job_type_part-time"> Part Time</label>| </li>
					<li><label class=" pe-2 temporary"><input class="shadow-none" type="checkbox" name="filter_job_type[]" value="temporary" checked="checked" id="job_type_temporary"> Temporary</label>| </li>
			    </ul>
            </div>
        </div>
    </div>
    <!-- end careers section -->

    <section id="blog" class="blog pt-2" >
        <div class="container" data-aos="fade-up">
            {% for career in careers %}
            <div class="row bg-white shadow py-2 my-2 ">
                <div class="col-md-2">
                    <div class="pt-1">
                        <img src="{{career.company_logo.url}}" alt="" class="img-fluid h-75 w-75">
                    </div>
                </div>
                <div class="col-md-6">
                    <a href="{% url 'careers:career_detail' career.slug %}"  >
                        <div class="pt-2">
                            {{career.job_title}}
                        </div>
                    </a>

                </div>
                <div class="col-md-2">
                    <div class="text-muted pt-3"> {{career.location}}</div>
                </div>
                <div class="col-md-2">
                    <div class="text-muted pt-3"> 3 month ago.</div>
                </div>
            </div>
            {% endfor %}

          
          
          
  
          
            <div class="blog-pagination">
                {% if is_paginated %}
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="" href="#">&laquo;</a>
                        </li>
                    {% endif %}
      
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active"><a >{{ i }}</a></li>
                        {% else %}
                            <li class="page-item">
                                <a class="" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
      
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a href="?page={{ page_obj.next_page_number }}" class="">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="">&raquo;</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
      
              </div>
  
        </div>
      </section>

  </main>
  <!-- End #main -->

{% endblock %}