Goldplayers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('about/',include('about.urls')),
    path('resources/', include('news.urls')),
    path('account/', include('account.urls')),
    path('careers/', include('careers.urls')),
    path('dashboard/',include('app2.urls')),
    path('ckeditor/' ,include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

about/urls.py
from django.urls import path
from . import views
from .views import AboutDetailView
app_name ='about'


urlpatterns = [
    path('', AboutDetailView.as_view(), name='about_us'),
]

account/urls.py
from django.urls import path
from . import views
app_name ='account'


urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.userlogout, name="logout"),
    path('profile', views.userprofile, name ="profile"),
    path('change/password', views.change_password_view, name='change_password'),
]

app/urls.py
from django.urls import path
from . import views
from .views import IndexView,SolutionDetailView,SolutionSubDetailView,SectorbDetailView,LocationsList,TestimonialsListView
app_name ='app'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about-us',views.aboutus, name='about'),
    path('solution',views.solution, name='solution'),
    path('solution/<slug:slug>',SolutionDetailView.as_view(), name='solution_detail'),
    path('solution/detail/<slug:slug>',SolutionSubDetailView.as_view(), name='solution_sub_detail'),
    path('sectors', views.sectors, name='sectors'),
    path('sectors/<slug:slug>', SectorbDetailView.as_view(), name='sector_detail'),
    path('location', LocationsList.as_view(), name='location'),
    path('testimonials', TestimonialsListView.as_view(), name='testimonials'),
]

app2/urls.py
from django.urls import path
from . import views 
from . views import *


app_name ='dashboard'

urlpatterns = [
        path('',views.index,name='index'),

        path('banners/', BannarListView.as_view(), name="banners"),
        path('banners/create', BannerCreateView.as_view(), name='banner_create'),
        path('banners/delete/<int:id>', views.delete_banner, name='banner_delete'),

        path('about/', views.aboutUs, name='about'),
        path('about/organizatin/setting', views.organizationsetting, name='organizations_setting'),
        path('about/objectives/add',ObjectiveCreatView.as_view(), name='objective_create'),
        path('about/objective',ObjectivesListView.as_view(), name='objective'),
        path('about/objective/detail/<int:id>',ObjectivesDetailView.as_view(), name='objective_detail'),
        path('about/objective/delete/<int:id>', views.objective_delete, name='objective_delete'),
        path('location', LocationListView.as_view(), name='locations'),
        path('location/add', LocationCreateView.as_view(), name='add_new_location'),
        path('location/update/<int:id>',LocationUpdateDetailView.as_view(), name='location_detail_update'),
        path('location/delete/<int:id>', views.location_delete, name='delete_location'),
        path('office', OfficeLocationListView.as_view(), name='office'),
        path('office/add', OfficeLocationCreateView.as_view(), name='add_office'),
        path('office/update/<int:id>',OfficeUpdateDetailView.as_view(),name='office_detail_update'),
        path('office/delete/<int:id>',views.office_delete, name='office_delete'),

        path('career/category', CareerCategoryListView.as_view(), name='career_category'),
        path('career/category/delete/<int:id>',views.delete_career_category, name='delete_category'),
        path('career/category/update',views.update_category, name='category_update'),

        path('careers', CareerListView.as_view(), name='careers_list'),
        path('careers/add',CareerCreateView.as_view(), name='career_create'),
        path('careers/update/<int:id>',CareerUpdateView.as_view(), name='career_update'),
        path('careers/delete/<int:id>', views.delete_career,name='delete_career'),

        path('testimonials', TestimonialsListView.as_view(), name='testimonials'),
        path('testimonials/add', TestimonialsCreateView.as_view(), name='testimonials_add'),
        path('testimonials/update/<int:id>', TestimonialsUpdateView.as_view(), name='testimonials_update'),
        path('testimonials/delete/<int:id>', views.delete_testimonials, name='delete_testimonials'),

        path('clients', ClientListCreateView.as_view(), name='client_list'),
        path('clients/delete/<int:id>',views.delete_client, name='delete_client'),


        path('resources/<slug:resource_type>',NewsResourcesListView.as_view(), name='resources_news'),
        path('resources/create/<slug:resource_type>/', NewsResourcesCreateView.as_view(), name='news_resources_create'),
        path('resources/update/<slug:slug>',NewsResourcesUpdateView.as_view(), name='resource_update'),
        path('resources/delete/<slug:slug>', views.delete_resources,name='delete_resources'),


        path('about/sector', views.aboutSector, name='about_sector'),
        path('sectors',SectorListView.as_view(), name='sectors'),
        path('sectors/create',SectorCreateView.as_view(), name='sector_create'),
        path('sectors/update/<slug:slug>',SectorUpdateView.as_view(), name='update_sector'),
        path('sectors/delete/<slug:slug>', views.delete_sectors, name='delete_sectors'),


        path('about/solution', views.aboutSolution, name='solution'),
        path('solutions', SolutionListView.as_view(), name='solution_list'),
        path('solutions/create', SolutionCreateView.as_view(), name='solution_create'),
        path('solutions/update/<slug:slug>', SolutionUpdateView.as_view(), name='solution_update'),
        path('solutions/delete/<slug:slug>', views.delete_solution, name='delete_solution'),


        path('solution/sub-category',SolutionSubCategoryListView.as_view(), name='solution_sub_category'),
        path('solution/sub-category/create',SolutionSubCategoryCreateView.as_view(), name='solution_sub_category_create'),
        path('solution/sub-category/update/<slug:slug>',SolutionSubCategoryUpdateView.as_view(), name='solution_sub_category_update'),
        path('solution/sub-category/delete/<slug:slug>', views.delete_SolutionSubCategor, name='delete_solution_sub_category'),


        path('associated/company',AssocialtedCompanyListView.as_view(), name='associated_company_list'),
        path('associated/company/create',AssociatedCreateView.as_view(), name='associated_company_create'),
        path('associated/compnay/update/<int:id>',AssociatedCompanyUpdateView.as_view(), name='associated_company_update'),
        path('associated/company/delete/<int:id>', views.delete_Associated_company, name='associated_company_delete'),


]

careers/urls.py
from django.urls import path
from . import views
from .views import CareersListView,CareerDetailView
app_name ='careers'


urlpatterns = [
    path('', CareersListView.as_view(), name='careers'),
    path('<slug:slug>', CareerDetailView.as_view(), name='career_detail'),
]

news/urls.py
from django.urls import path
from . import views
from .views import ResourcseListView,ResourceDetailView,NewsResourcseListView,InsightsResourcseListView,CaseStudiesResourcseListView
app_name ='resources'


urlpatterns = [
    path('', ResourcseListView.as_view(), name='all_resources'),
    path('detail/<slug:slug>', ResourceDetailView.as_view(), name='resource_detail'),
    path('news',NewsResourcseListView.as_view(), name='resources_news'),
    path('insights',InsightsResourcseListView.as_view(), name='resources_insight'),
    path('case-studies',CaseStudiesResourcseListView.as_view(), name='resources_case_studies'),

]

about/models.py
from django.db import models
from ckeditor.fields import RichTextField


'''organization setting'''
class OrganizationSetting(models.Model):
    logo =models.ImageField(verbose_name='Organization Logo',upload_to='aboutus/')
    fav_icon = models.ImageField(verbose_name='Organization Fav Icon',upload_to='aboutus/')
    site_name = models.CharField(verbose_name='Organization Name',max_length=150)
    location = models.CharField(verbose_name='Organizaton Location', max_length=200)
    phone_number = models.CharField(verbose_name='Organization Phone Number',max_length=150)
    email = models.EmailField(verbose_name='Organization Email')
    fb_url = models.URLField(verbose_name='Facebook Page URL', null=True,blank=True)
    tw_url = models.URLField(verbose_name='Twitter URL', null=True,blank=True)
    insta_url = models.URLField(verbose_name='Instagram Page URL', null=True,blank=True)
    linkedin_url = models.URLField(verbose_name='Linkedin URL', null=True,blank=True)



    def __str__(self) -> str:
        return self.site_name




'''about '''
class About(models.Model):
    title = models.CharField(verbose_name='About Title',max_length=150)
    image = models.ImageField(verbose_name='About Image',upload_to='aboutus/')
    short_descriptions = RichTextField(verbose_name='About Short Descriptions')
    descriptions = RichTextField(verbose_name='About Descriptions')

    def __str__(self) -> str:
        return self.title


''' company objectives model '''
class Objective(models.Model):
    title = models.CharField(verbose_name='Objective Title',max_length=150)
    image = models.ImageField(verbose_name='Objective Image',upload_to='aboutus/')
    descriptions = RichTextField(verbose_name='Descriptions')

    class Meta:
        ordering =['id']
        verbose_name = 'Our Objective'
        verbose_name_plural = "Our Objectives"



    def __str__(self) -> str:
        return self.title

careers/models.py
from django.db import models
from autoslug import AutoSlugField
from ckeditor.fields import RichTextField

''' career category'''
class Category(models.Model):
    category_name = models.CharField(verbose_name='Career Category Name' ,max_length=150)


    def __str__(self):
        return self.category_name
    
''' career types '''
JOB_TYPE_CHOICES = [
        ('full_time', 'Full Time'),
        ('part_time', 'Part Time'),
        ('freelance', 'Freelance'),
        ('internship','Internship'),
        ('temporary','Temporary')
    ]


'''career model '''
class Careers(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_DEFAULT, default=None, null=True, blank=True, verbose_name='Choose Career Category')
    company_logo = models.ImageField(upload_to='careerimage/', verbose_name='Company Logo *')
    job_title = models.CharField(verbose_name='Job Title *', max_length=150)
    location = models.CharField(verbose_name='Location *', max_length=150)
    salary = models.CharField(verbose_name='Salary *', max_length=150, null=True, blank=True)
    created_date = models.DateTimeField(auto_now=True)
    valid_date = models.DateField(verbose_name='Valid Date *')
    job_type = models.CharField(verbose_name='Job Type *', max_length=20, choices=JOB_TYPE_CHOICES, default='full_time')
    descriptions = RichTextField(verbose_name='Job Descriptions(responsibility,qualification) *')
    slug = AutoSlugField(populate_from ='job_title', default=None, unique=True)

    class Meta:
        ordering =['-id']

    def __str__(self):
        return str(self.job_title)
    

about/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from about.models import About,Objective
from news.models import Resources
from app.models import Client
from django.views import generic


class AboutDetailView(generic.DetailView):
    model = About
    template_name = 'about/about.html'
    context_object_name = 'about_us'  

    def get_object(self, queryset=None):
        return About.objects.first() 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['about_us'] = self.get_object()
        context['objectives'] = Objective.objects.all()
        context['resources'] = Resources.objects.all()[:4]
        context['clients'] = Client.objects.all()
        return context

careers/views.py
from typing import Any
from django.shortcuts import render
from . models import Careers
from django.views import generic
from .froms import JobSearchForm


'''careers view '''
class CareersListView(generic.ListView):
    model = Careers
    template_name ='careers/careers.html'
    context_object_name= 'careers'
    paginate_by =5

    def get_queryset(self):
        queryset = super().get_queryset()
        form = JobSearchForm(self.request.GET)

        if form.is_valid():
            keywords = form.cleaned_data.get('keywords')
            location = form.cleaned_data.get('location')
            category = form.cleaned_data.get('category')

            if keywords:
                queryset = queryset.filter(job_title__icontains=keywords)
            if location:
                queryset = queryset.filter(location__icontains=location)
            if category:
                queryset = queryset.filter(category=category)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = JobSearchForm(self.request.GET)
        return context

'''career detail'''
class CareerDetailView(generic.DetailView):
    model = Careers 
    template_name ='careers/career_detail.html'
    context_object_name ='career_detail'
    slug_url_kwarg = 'slug'

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>
    {{organization_settings.site_name}} - 
    {% block title %}

    {% endblock %}
  </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{organization_settings.fav_icon.url}}" rel="icon">
  <link href="{{organization_settings.fav_icon.url}}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'app/assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'app/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'app/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'app/assets/css/style.css' %}" rel="stylesheet">

  <!-- carsoule -->
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,400;0,700;1,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" >
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
       
        <i class="bi bi-envelope d-flex align-items-center ms-4">
            <a href="mailto:{{ organization_settings.email }}">Contact us</a>
        </i>
       
        <i class="bi bi-phone d-flex align-items-center ms-4">
            <a href="tel:{{ organization_settings.phone_number }}"> Phone Number: {{organization_settings.phone_number}}</a>
        </i>

        <i class="bi bi-person-add d-flex align-items-center ms-4">
            <a href="{% url 'careers:careers' %}">Careers</a>
        </i>

       
      </div>
      <div class="social-links contact-info d-none d-md-flex align-items-center">
        <i class="ms-2 bi bi-journal-text pe-2">
            <a href="">Vendor Register</a>
        </i>
        <span class="text-white">|</span>
        
        {% if request.user.is_authenticated %}
        <nav id="navbar" class="navbar">
          <ul>
            <li class="dropdown">
              <a href="" class="text-white">
                {% if request.user.name %}{{request.user.name}}{% else %}{{ request.user.email}}{% endif %}
                <i class="bi bi-chevron-down"></i>
              </a>
              <ul>
                <li class="text-dark pt-2 d-flex ps-3 ">
                  <i class="bi bi-person-badge text-dark fs-6"></i>
                  <a href="{% url 'account:profile' %}" class="ps-0 text-dark fs-6">Profile</a>
                </li>
                {% if request.user.is_admin %}
                <li class="text-dark  d-flex ps-3 pt-2 ">
                  <i class="bi bi-gear text-dark fs-6"></i>
                  <a href="{% url 'dashboard:index' %}" class="ps-0 text-dark fs-6" target="_blank">Dashboard</a>
                </li>
                {% endif %}
                <li class="text-dark  d-flex ps-3 pt-2">
                  <i class="bi bi-box-arrow-left text-dark fs-6"></i>
                  <a href="{% url 'account:logout' %}" class="ps-0  text-dark fs-6">
                    Logout
                  </a>
                </li>
                
              </ul>
            </li> 
          </ul>
        </nav>
        
        <span class="text-white">|</span>
        {% else%}    
        <i class="ms-2 bi bi-globe-americas pe-2"><a href="{% url 'account:login' %}">Login</a></i>
        <span class="text-white">|</span>
        {% endif %}



        
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex justify-content-between align-items-center">

      <div class="logo">
        <h1 class="p-0"><a href="/"><img src="{{organization_settings.logo.url}}" class="img-fluid "></a></h1>
      </div>

      <nav id="navbar" class="navbar ">
        <ul>
          <li class="dropdown">
            <a href="{% url 'about:about_us' %}">
                <span>About</span> 
            </a>
            
          </li>  
          
          <li class="dropdown">
            <a href="{% url 'app:solution' %}">
                <span>Solution</span> 
                <i class="bi bi-chevron-down"></i>
            </a>
            <ul>

              {% for category in solution_category%}
              <li class="dropdown">
                <a href="{% url 'app:solution_detail' category.slug %}">
                  <span>{{category.title}}</span> 
                  <i class="bi bi-chevron-right"></i>
                </a>
                {% if category.solution_sub_category%}
                <ul>
                  {% for sub_category in category.solution_sub_category.all %}
                  <li><a href="{% url 'app:solution_sub_detail' sub_category.slug %}">{{sub_category.sub_category_name}}</a></li>
                  {% endfor %}
                </ul>
                {% endif %}
              </li>

              {% endfor %}
              
             
            </ul>
          </li>   

          <li class="dropdown">
            <a href="{% url 'app:sectors' %}">
                <span>Sectors</span> 
                <i class="bi bi-chevron-down"></i>
            </a>
            <ul>
              {% for sector in secotrs%}
              <li>
                <a href="{% url 'app:sector_detail' sector.slug %}">{{sector.title}}</a>
              </li>
              {% endfor %}
              
            </ul>
          </li>  
          
          <li class="dropdown">
            <a href="{% url 'app:location' %}">
                <span>Locations</span> 
            </a>
            
          </li> 
          

          

          <li class="dropdown">
            <a href="{% url 'resources:all_resources' %}">
                <span>Resources</span> 
                <i class="bi bi-chevron-down"></i>
            </a>
            <ul>
              <li><a href="{% url 'resources:resources_news' %}">News</a></li>
              <li><a href="{% url 'resources:resources_insight' %}">Insights</a></li>
              <li><a href="{% url 'resources:resources_case_studies' %}">Case Studies</a></li>
            </ul>
          </li>   

          <li class="dropdown">
            <a href="{% url 'app:testimonials' %}">
                <span>Testimonials</span> 
            </a>
            
          </li>   

          <li class="dropdown">
            <a href="{% url 'careers:careers' %}">
                <span>Careers</span> 
            </a>
            
          </li>  

        </ul>
        <div class="">
          <i class="bi bi-list mobile-nav-toggle"></i>
        </div>
      </nav><!-- .navbar -->
      <i class="bi mobile-nav-toggle bi-x"></i>
    </div>
  </header><!-- End Header -->

 



<div class="navbar-collapse">
  <ul class="pmenu">
    {% for company in associated_companies %}
    <li>
      <a class="scroll" href="{{company.website_url}}" target="_blank">
        <img src="{{company.company_logo.url}}" class="img-fluid object-fit-cover h-100">
        <span>{{company.company_name}}</span>
      </a>
    </li>
    {% endfor %}
  </ul>
</div>


{% block content %}

{% endblock %}



<!-- ======= Footer ======= -->
<footer id="footer">
    <div class="footer-top">
      <div class="container" style="background-image:url(https://www.imdaad.ae/wp-content/themes/imdaad-1.1/img/logo-bg.png);  
         background-size: contain;
         background-repeat: no-repeat;
         background-position: top center;
         height: auto;
         ">

         <div class="footer-top">
          <div class="container">
            <div class="row">
    
              <div class=" col-md-6 col-lg-3 footer-links">
                <h4>RESOURCES</h4>
                <ul>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                  <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                </ul>
              </div>
    
              <div class=" col-md-6 col-lg-3 footer-links">
                <h4>Our Locations</h4>
                <ul>
                  {% for location in office_locations %}
                  <li>
                    <i class="bx bx-chevron-right"></i> 
                    <a href="{{location.map_url}}" target="_blank">{{location.office_name}}</a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
    
              <div class=" col-md-6 col-lg-3 footer-contact">
                <h4>Contact Us</h4>
                <p>
                 {{organization_settings.location}}
                </p>
                <strong>General Inquiries</strong>
                <br>
                <strong>Phone:</strong> 
                <a class="text-white hover:text-danger" href="tel:{{ organization_settings.phone_number }}">{{organization_settings.phone_number}}</a>
                <br>
                <b>Email:</b><a href="mailto:{{ organization_settings.email }}" class="text-white"> {{organization_settings.email}}</a><br>
                
    
              </div>
    
              <div class=" col-md-6 col-lg-3 footer-info">
                <h3>About Eterna</h3>
                <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
                <div class="social-links mt-3">
                  {% if organization_settings.tw_url %}
                  <a href="{{organization_settings.tw_url}}" target="_blank" class="twitter"><i class="bx bxl-twitter"></i></a>
                  {%endif %}
                  {% if organization_settings.fb_url %}
                  <a href="{{organization_settings.fb_url}}"  target="_blank" class="facebook"><i class="bx bxl-facebook"></i></a>
                  {% endif %}

                  {% if organization_settings.fb_url %}
                  <a href="{{organization_settings.insta_url}}" target="_blank" class="instagram"><i class="bx bxl-instagram"></i></a>
                  {% endif %}

                  {% if organization_settings.linkedin_url %}
                  <a href="{{organization_settings.linkedin_url}}" target="_blank" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                  {% endif %}
                </div>
              </div>
    
            </div>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>{{organization_settings.site_name}}</span></strong>. All Rights Reserved
      </div>
      <div class="credits">Designed by <a href="https://kitwosd.com/">Kitwosd .</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'app/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'app/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'app/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'app/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'app/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'app/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'app/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'app/assets/js/main.js' %}"></script>


</body>

</html>

app/templates/app/sectors_detail.html
{% extends 'app/base.html' %}
{% load static %} 
{% block title %}
{{detail.title}}
{% endblock %}
{% block content %}
  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs" 
    style="background-image:url(https://www.imdaad.ae/wp-content/uploads/2023/11/Group-01.webp);
    background-size:cover;">
      <div class="container">

        <ol>
          <li><a href="/" class="text-white">Home</a></li>
          <li class="text-white">Solution </li>
        </ol>
        <h2 class="text-white">{{detail.title}} </h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <!-- ======= About Section ======= -->
    <section id="about" class="about pb-0">
      <div class="container">

        <div class="row">
          <div class="col-lg-4 ">
            <img src="{{detail.image.url}}" class="img-fluid  object-fit-cover" alt="">
          </div>
          <div class="col-lg-8 pt-lg-0 content">
            <h3>{{detail.title}}</h3>
            <p class="fst-italic">
              {{detail.short_descriptions|safe}}
            </p>
           
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <p>
              {{detail.descriptions|safe}}  
            </p>

          </div>
        </div>
        <!-- image section -->
       

      </div>
      <div class="rectangle_line"></div>

    </section>

    <!-- End About Section -->

   

    

    <!-- SECTORS section start -->
    <section id="services" class="services pb-5">
        <div class="container">
    
          <div class="row justify-content-center ">
            {% for sector in secotrs %}
            <div class="col-6 col-lg-2 col-md-6 d-flex align-items-stretch mb-4">
              <a href="{% url 'app:sector_detail' sector.slug %}">
              <div class="icon-box pt-4 pb-3">
                <div class="icon">
                  <img src="{{ sector.icon_image.url }}" class="img-fluid" height="50" width="50">
                </div>
                <h4><a href="{% url 'app:sector_detail' sector.slug %}" class="fs-6">{{sector.title}}</a></h4>
              </div>
            </a>
            </div>
            {% endfor %}
    
            
           
    
          </div>
          
    
        </div>
      </section>
      
    <!--END SECTORS section start -->

   
  </main><!-- End #main -->

  {% endblock %}